import type {
  Address,
  BlogAuthor,
  BlogPost,
  Brand,
  Category,
  Coupon,
  Order,
  Product,
  Question,
  Review,
  ShippingOption,
} from "./types";

/* ------------------------------------------------------------------
   Dados de demonstração. Substitua por chamadas à sua API/CMS.
   ------------------------------------------------------------------ */

export const categories: Category[] = [
  {
    slug: "vestidos",
    name: "Vestidos",
    description: "Silhuetas fluidas e cortes precisos para cada momento do dia.",
    art: "dress",
    subcategories: [
      { slug: "midi", name: "Midi" },
      { slug: "longos", name: "Longos" },
      { slug: "curtos", name: "Curtos" },
      { slug: "festa", name: "Festa" },
    ],
  },
  {
    slug: "blusas",
    name: "Blusas & Camisas",
    description: "Tecidos nobres, caimento leve e acabamento impecável.",
    art: "blouse",
    subcategories: [
      { slug: "camisas", name: "Camisas" },
      { slug: "blusas", name: "Blusas" },
      { slug: "tricot", name: "Tricot" },
    ],
  },
  {
    slug: "calcas",
    name: "Calças",
    description: "Alfaiataria contemporânea que alonga e valoriza.",
    art: "pants",
    subcategories: [
      { slug: "alfaiataria", name: "Alfaiataria" },
      { slug: "wide-leg", name: "Wide Leg" },
      { slug: "jeans", name: "Jeans" },
    ],
  },
  {
    slug: "saias",
    name: "Saias",
    description: "Do midi plissado ao lápis acetinado.",
    art: "skirt",
    subcategories: [
      { slug: "midi", name: "Midi" },
      { slug: "mini", name: "Mini" },
    ],
  },
  {
    slug: "casacos",
    name: "Casacos & Blazers",
    description: "Camadas com estrutura e sofisticação.",
    art: "blazer",
    subcategories: [
      { slug: "blazers", name: "Blazers" },
      { slug: "trench", name: "Trench Coats" },
    ],
  },
  {
    slug: "macacoes",
    name: "Macacões",
    description: "Uma peça, um look completo.",
    art: "jumpsuit",
    subcategories: [
      { slug: "longos", name: "Longos" },
      { slug: "curtos", name: "Curtos" },
    ],
  },
  {
    slug: "acessorios",
    name: "Acessórios",
    description: "O detalhe que assina o visual.",
    art: "bag",
    subcategories: [
      { slug: "bolsas", name: "Bolsas" },
      { slug: "joias", name: "Joias" },
      { slug: "calcados", name: "Calçados" },
    ],
  },
  {
    slug: "praia",
    name: "Moda Praia",
    description: "Resortwear para dias de sol.",
    art: "swim",
    subcategories: [
      { slug: "biquinis", name: "Biquínis" },
      { slug: "saidas", name: "Saídas de Praia" },
    ],
  },
];

export const brands: Brand[] = [
  {
    slug: "km-atelier",
    name: "KM Atelier",
    tagline: "Alta costura acessível",
    description:
      "A linha assinatura da Karen Michelly: peças desenhadas no nosso ateliê, produzidas em pequenas tiragens com tecidos selecionados.",
    origin: "São Paulo, Brasil",
  },
  {
    slug: "km-essentials",
    name: "KM Essentials",
    tagline: "O guarda-roupa essencial",
    description:
      "Básicos de luxo pensados para durar: modelagens atemporais, cores neutras e conforto absoluto.",
    origin: "Minas Gerais, Brasil",
  },
  {
    slug: "km-noir",
    name: "KM Noir",
    tagline: "Para noites inesquecíveis",
    description:
      "Festa e ocasião. Brilho na medida, cetim, crepe e transparências elegantes.",
    origin: "Rio de Janeiro, Brasil",
  },
  {
    slug: "maison-dore",
    name: "Maison Doré",
    tagline: "Acessórios com alma",
    description:
      "Bolsas em couro, joias banhadas a ouro 18k e calçados feitos à mão por artesãos brasileiros.",
    origin: "Franca, Brasil",
  },
];

const care = [
  "Lavar à mão com água fria",
  "Não usar alvejante",
  "Secar à sombra",
  "Passar em temperatura baixa",
];

export const products: Product[] = [
  {
    id: "p1",
    slug: "vestido-midi-cetim-aurora",
    name: "Vestido Midi Cetim Aurora",
    category: "vestidos",
    subcategory: "midi",
    brand: "km-atelier",
    price: 689.9,
    oldPrice: 789.9,
    rating: 4.9,
    reviewsCount: 128,
    colors: [
      { name: "Champagne", hex: "#D8C3A5" },
      { name: "Preto", hex: "#0D0D0D" },
      { name: "Nude", hex: "#E8D8D2" },
    ],
    sizes: ["PP", "P", "M", "G", "GG"],
    stock: "disponivel",
    isBestseller: true,
    description:
      "Cetim de toque acetinado com caimento enviesado, alças finas reguláveis e fenda lateral discreta. Uma peça que transita do jantar ao evento com a mesma elegância.",
    details: ["Corte enviesado", "Alças reguláveis", "Fenda lateral", "Forro interno"],
    composition: "97% Poliéster, 3% Elastano",
    care,
    art: "dress",
    tone: 0,
    sold: 980,
    createdAt: "2026-08-20",
  },
  {
    id: "p2",
    slug: "camisa-seda-lumiere",
    name: "Camisa de Seda Lumière",
    category: "blusas",
    subcategory: "camisas",
    brand: "km-atelier",
    price: 459.9,
    rating: 4.8,
    reviewsCount: 86,
    colors: [
      { name: "Off-White", hex: "#F7F4EF" },
      { name: "Champagne", hex: "#D8C3A5" },
    ],
    sizes: ["P", "M", "G"],
    stock: "disponivel",
    isNew: true,
    description:
      "Camisa em seda pura com botões perolados e punhos alongados. Use aberta sobre top ou fechada com alfaiataria.",
    details: ["Seda pura", "Botões perolados", "Punho duplo"],
    composition: "100% Seda",
    care,
    art: "blouse",
    tone: 1,
    sold: 410,
    createdAt: "2026-09-28",
  },
  {
    id: "p3",
    slug: "calca-alfaiataria-milano",
    name: "Calça Alfaiataria Milano",
    category: "calcas",
    subcategory: "alfaiataria",
    brand: "km-essentials",
    price: 429.9,
    rating: 4.7,
    reviewsCount: 203,
    colors: [
      { name: "Preto", hex: "#0D0D0D" },
      { name: "Areia", hex: "#CDBBA3" },
    ],
    sizes: ["36", "38", "40", "42", "44"],
    stock: "disponivel",
    isBestseller: true,
    description:
      "Cintura alta, pregas frontais e barra italiana. A calça que alonga a silhueta e resolve qualquer produção.",
    details: ["Cintura alta", "Pregas frontais", "Bolsos faca", "Barra italiana"],
    composition: "68% Poliéster, 30% Viscose, 2% Elastano",
    care,
    art: "pants",
    tone: 2,
    sold: 1320,
    createdAt: "2026-05-11",
  },
  {
    id: "p4",
    slug: "blazer-alongado-veneza",
    name: "Blazer Alongado Veneza",
    category: "casacos",
    subcategory: "blazers",
    brand: "km-atelier",
    price: 899.9,
    oldPrice: 1099.9,
    rating: 4.9,
    reviewsCount: 64,
    colors: [
      { name: "Preto", hex: "#0D0D0D" },
      { name: "Off-White", hex: "#F7F4EF" },
    ],
    sizes: ["P", "M", "G"],
    stock: "disponivel",
    isBestseller: true,
    description:
      "Blazer de corte alongado, ombros estruturados e botões dourados. Peça-chave de um guarda-roupa sofisticado.",
    details: ["Ombreiras leves", "Botões dourados", "Forro acetinado"],
    composition: "Crepe de lã fria",
    care: ["Lavagem a seco", "Passar a vapor"],
    art: "blazer",
    tone: 3,
    sold: 640,
    createdAt: "2026-06-01",
  },
  {
    id: "p5",
    slug: "saia-midi-plissada-sienna",
    name: "Saia Midi Plissada Sienna",
    category: "saias",
    subcategory: "midi",
    brand: "km-essentials",
    price: 349.9,
    rating: 4.6,
    reviewsCount: 51,
    colors: [
      { name: "Nude", hex: "#E8D8D2" },
      { name: "Dourado", hex: "#C6A15B" },
    ],
    sizes: ["P", "M", "G"],
    stock: "disponivel",
    isNew: true,
    description:
      "Plissado permanente com brilho acetinado e cós elástico embutido. Movimento a cada passo.",
    details: ["Plissado permanente", "Cós elástico", "Comprimento midi"],
    composition: "100% Poliéster",
    care,
    art: "skirt",
    tone: 1,
    sold: 290,
    createdAt: "2026-09-30",
  },
  {
    id: "p6",
    slug: "bolsa-couro-iris",
    name: "Bolsa de Couro Íris",
    category: "acessorios",
    subcategory: "bolsas",
    brand: "maison-dore",
    price: 1290.0,
    rating: 5,
    reviewsCount: 39,
    colors: [
      { name: "Preto", hex: "#0D0D0D" },
      { name: "Caramelo", hex: "#A87B4F" },
    ],
    sizes: ["Único"],
    stock: "disponivel",
    isBestseller: true,
    description:
      "Couro legítimo com ferragens banhadas a ouro, alça de mão e alça transversal removível.",
    details: ["Couro legítimo", "Ferragens douradas", "Alça removível"],
    composition: "Couro bovino",
    care: ["Limpar com pano seco", "Guardar no dust bag"],
    art: "bag",
    tone: 0,
    sold: 220,
    createdAt: "2026-04-10",
  },
  {
    id: "p7",
    slug: "scarpin-bico-fino-nuit",
    name: "Scarpin Bico Fino Nuit",
    category: "acessorios",
    subcategory: "calcados",
    brand: "maison-dore",
    price: 589.9,
    oldPrice: 689.9,
    rating: 4.7,
    reviewsCount: 92,
    colors: [
      { name: "Preto", hex: "#0D0D0D" },
      { name: "Nude", hex: "#E8D8D2" },
    ],
    sizes: ["34", "35", "36", "37", "38", "39"],
    stock: "disponivel",
    description: "Salto 9cm, couro envernizado e palmilha acolchoada para conforto prolongado.",
    details: ["Salto 9cm", "Palmilha acolchoada", "Bico fino"],
    composition: "Couro envernizado",
    care: ["Limpar com flanela"],
    art: "heels",
    tone: 2,
    sold: 510,
    createdAt: "2026-03-15",
  },
  {
    id: "p8",
    slug: "macacao-longo-crepe-lyon",
    name: "Macacão Longo Crepe Lyon",
    category: "macacoes",
    subcategory: "longos",
    brand: "km-noir",
    price: 749.9,
    rating: 4.8,
    reviewsCount: 44,
    colors: [{ name: "Preto", hex: "#0D0D0D" }],
    sizes: ["P", "M", "G", "GG"],
    stock: "esgotado",
    description:
      "Crepe encorpado, decote V profundo e pernas amplas. Faixa na cintura para marcar a silhueta.",
    details: ["Decote V", "Faixa na cintura", "Pernas amplas"],
    composition: "95% Poliéster, 5% Elastano",
    care,
    art: "jumpsuit",
    tone: 3,
    sold: 330,
    createdAt: "2026-07-22",
  },
  {
    id: "p9",
    slug: "tricot-gola-alta-cashmere",
    name: "Tricot Gola Alta Cashmere",
    category: "blusas",
    subcategory: "tricot",
    brand: "km-essentials",
    price: 529.9,
    rating: 4.9,
    reviewsCount: 75,
    colors: [
      { name: "Off-White", hex: "#F7F4EF" },
      { name: "Champagne", hex: "#D8C3A5" },
      { name: "Preto", hex: "#0D0D0D" },
    ],
    sizes: ["P", "M", "G"],
    stock: "disponivel",
    isNew: true,
    description: "Mistura de cashmere e lã merino, toque macio e gola alta dobrável.",
    details: ["Gola alta", "Punhos canelados", "Toque macio"],
    composition: "30% Cashmere, 70% Lã Merino",
    care: ["Lavar à mão", "Secar na horizontal"],
    art: "knit",
    tone: 0,
    sold: 260,
    createdAt: "2026-09-25",
  },
  {
    id: "p10",
    slug: "trench-coat-classico-london",
    name: "Trench Coat Clássico London",
    category: "casacos",
    subcategory: "trench",
    brand: "km-atelier",
    price: 1190.0,
    rating: 4.8,
    reviewsCount: 31,
    colors: [
      { name: "Areia", hex: "#CDBBA3" },
      { name: "Preto", hex: "#0D0D0D" },
    ],
    sizes: ["P", "M", "G"],
    stock: "disponivel",
    description: "Gabardine com repelência à água, abotoamento duplo e faixa na cintura.",
    details: ["Abotoamento duplo", "Faixa na cintura", "Repele água"],
    composition: "100% Algodão gabardine",
    care: ["Lavagem a seco"],
    art: "coat",
    tone: 1,
    sold: 140,
    createdAt: "2026-08-02",
  },
  {
    id: "p11",
    slug: "colar-elos-dourados-soleil",
    name: "Colar Elos Dourados Soleil",
    category: "acessorios",
    subcategory: "joias",
    brand: "maison-dore",
    price: 289.9,
    rating: 4.6,
    reviewsCount: 58,
    colors: [{ name: "Dourado", hex: "#C6A15B" }],
    sizes: ["Único"],
    stock: "disponivel",
    isNew: true,
    description: "Elos encadeados banhados a ouro 18k com fecho lagosta. Hipoalergênico.",
    details: ["Banho ouro 18k", "Hipoalergênico", "45cm"],
    composition: "Latão banhado a ouro 18k",
    care: ["Evitar contato com perfume", "Guardar separado"],
    art: "necklace",
    tone: 2,
    sold: 470,
    createdAt: "2026-09-18",
  },
  {
    id: "p12",
    slug: "vestido-longo-festa-celeste",
    name: "Vestido Longo de Festa Celeste",
    category: "vestidos",
    subcategory: "festa",
    brand: "km-noir",
    price: 1490.0,
    oldPrice: 1790.0,
    rating: 5,
    reviewsCount: 22,
    colors: [
      { name: "Preto", hex: "#0D0D0D" },
      { name: "Champagne", hex: "#D8C3A5" },
    ],
    sizes: ["PP", "P", "M", "G"],
    stock: "disponivel",
    isBestseller: true,
    description:
      "Crepe com drapeado no ombro, costas abertas e cauda leve. Para noites que pedem presença.",
    details: ["Drapeado", "Costas abertas", "Cauda leve", "Bojo removível"],
    composition: "100% Poliéster crepe",
    care: ["Lavagem a seco"],
    art: "dress",
    tone: 3,
    sold: 190,
    createdAt: "2026-06-30",
  },
  {
    id: "p13",
    slug: "blusa-ombro-a-ombro-capri",
    name: "Blusa Ombro a Ombro Capri",
    category: "blusas",
    subcategory: "blusas",
    brand: "km-essentials",
    price: 239.9,
    oldPrice: 299.9,
    rating: 4.5,
    reviewsCount: 67,
    colors: [
      { name: "Off-White", hex: "#F7F4EF" },
      { name: "Nude", hex: "#E8D8D2" },
    ],
    sizes: ["P", "M", "G"],
    stock: "disponivel",
    description: "Linho leve com elástico no decote e mangas bufantes. Frescor com charme.",
    details: ["Decote ombro a ombro", "Mangas bufantes"],
    composition: "55% Linho, 45% Viscose",
    care,
    art: "blouse",
    tone: 2,
    sold: 380,
    createdAt: "2026-02-14",
  },
  {
    id: "p14",
    slug: "calca-wide-leg-linho-amalfi",
    name: "Calça Wide Leg Linho Amalfi",
    category: "calcas",
    subcategory: "wide-leg",
    brand: "km-essentials",
    price: 379.9,
    rating: 4.7,
    reviewsCount: 88,
    colors: [
      { name: "Off-White", hex: "#F7F4EF" },
      { name: "Areia", hex: "#CDBBA3" },
    ],
    sizes: ["36", "38", "40", "42"],
    stock: "disponivel",
    isNew: true,
    description: "Linho puro, pernas amplas e cós com passantes. Leveza para dias quentes.",
    details: ["Linho puro", "Pernas amplas", "Cós com passantes"],
    composition: "100% Linho",
    care,
    art: "pants",
    tone: 0,
    sold: 300,
    createdAt: "2026-09-20",
  },
  {
    id: "p15",
    slug: "vestido-curto-tweed-chloe",
    name: "Vestido Curto Tweed Chloé",
    category: "vestidos",
    subcategory: "curtos",
    brand: "km-atelier",
    price: 649.9,
    rating: 4.8,
    reviewsCount: 41,
    colors: [{ name: "Off-White", hex: "#F7F4EF" }],
    sizes: ["P", "M", "G"],
    stock: "indisponivel",
    description: "Tweed com fios metalizados, acabamento em franjas e botões joia.",
    details: ["Tweed metalizado", "Franjas", "Botões joia"],
    composition: "60% Algodão, 30% Poliéster, 10% Lurex",
    care: ["Lavagem a seco"],
    art: "dress",
    tone: 1,
    sold: 170,
    createdAt: "2026-05-05",
  },
  {
    id: "p16",
    slug: "saia-lapis-couro-eco-noir",
    name: "Saia Lápis Couro Eco Noir",
    category: "saias",
    subcategory: "mini",
    brand: "km-noir",
    price: 319.9,
    oldPrice: 459.9,
    rating: 4.4,
    reviewsCount: 29,
    colors: [{ name: "Preto", hex: "#0D0D0D" }],
    sizes: ["P", "M", "G"],
    stock: "disponivel",
    description: "Couro ecológico de toque macio, fenda posterior e zíper invisível.",
    details: ["Couro ecológico", "Zíper invisível", "Fenda posterior"],
    composition: "Poliuretano com base em viscose",
    care: ["Limpar com pano úmido"],
    art: "skirt",
    tone: 3,
    sold: 240,
    createdAt: "2026-01-28",
  },
  {
    id: "p17",
    slug: "biquini-hot-pant-riviera",
    name: "Biquíni Hot Pant Riviera",
    category: "praia",
    subcategory: "biquinis",
    brand: "km-essentials",
    price: 269.9,
    rating: 4.6,
    reviewsCount: 47,
    colors: [
      { name: "Preto", hex: "#0D0D0D" },
      { name: "Dourado", hex: "#C6A15B" },
    ],
    sizes: ["P", "M", "G"],
    stock: "disponivel",
    description: "Tecido com proteção UV50+, top cortininha e calcinha hot pant com argolas douradas.",
    details: ["Proteção UV50+", "Argolas douradas"],
    composition: "80% Poliamida, 20% Elastano",
    care: ["Enxaguar após o uso"],
    art: "swim",
    tone: 0,
    sold: 210,
    createdAt: "2026-09-10",
  },
  {
    id: "p18",
    slug: "camisa-oversized-algodao-sol",
    name: "Camisa Oversized Algodão Sol",
    category: "blusas",
    subcategory: "camisas",
    brand: "km-essentials",
    price: 289.9,
    rating: 4.6,
    reviewsCount: 112,
    colors: [
      { name: "Off-White", hex: "#F7F4EF" },
      { name: "Preto", hex: "#0D0D0D" },
    ],
    sizes: ["P", "M", "G", "GG"],
    stock: "disponivel",
    isBestseller: true,
    description: "Algodão egípcio de fio 100, modelagem ampla e barra assimétrica.",
    details: ["Algodão egípcio", "Barra assimétrica"],
    composition: "100% Algodão",
    care,
    art: "blouse",
    tone: 3,
    sold: 870,
    createdAt: "2026-03-02",
  },
  {
    id: "p19",
    slug: "macacao-alfaiataria-paris",
    name: "Macacão Alfaiataria Paris",
    category: "macacoes",
    subcategory: "longos",
    brand: "km-atelier",
    price: 699.9,
    oldPrice: 849.9,
    rating: 4.7,
    reviewsCount: 26,
    colors: [
      { name: "Off-White", hex: "#F7F4EF" },
      { name: "Preto", hex: "#0D0D0D" },
    ],
    sizes: ["P", "M", "G"],
    stock: "disponivel",
    description: "Alfaiataria fluida com gola lapela, cinto encapado e pernas retas.",
    details: ["Gola lapela", "Cinto encapado"],
    composition: "Crepe de viscose",
    care,
    art: "jumpsuit",
    tone: 1,
    sold: 150,
    createdAt: "2026-08-12",
  },
  {
    id: "p20",
    slug: "brincos-gota-perola-lune",
    name: "Brincos Gota Pérola Lune",
    category: "acessorios",
    subcategory: "joias",
    brand: "maison-dore",
    price: 189.9,
    rating: 4.9,
    reviewsCount: 140,
    colors: [{ name: "Dourado", hex: "#C6A15B" }],
    sizes: ["Único"],
    stock: "disponivel",
    isBestseller: true,
    description: "Pérola shell em gota com base banhada a ouro 18k.",
    details: ["Pérola shell", "Banho ouro 18k"],
    composition: "Latão banhado, pérola shell",
    care: ["Guardar separado"],
    art: "necklace",
    tone: 0,
    sold: 1100,
    createdAt: "2026-02-01",
  },
  {
    id: "p21",
    slug: "vestido-longo-linho-provence",
    name: "Vestido Longo Linho Provence",
    category: "vestidos",
    subcategory: "longos",
    brand: "km-essentials",
    price: 559.9,
    rating: 4.7,
    reviewsCount: 58,
    colors: [
      { name: "Off-White", hex: "#F7F4EF" },
      { name: "Nude", hex: "#E8D8D2" },
    ],
    sizes: ["P", "M", "G"],
    stock: "disponivel",
    isNew: true,
    description: "Linho com botões frontais, faixa amarrada e saia em camadas.",
    details: ["Botões frontais", "Faixa amarrada", "Bolsos laterais"],
    composition: "100% Linho",
    care,
    art: "dress",
    tone: 2,
    sold: 260,
    createdAt: "2026-10-01",
  },
  {
    id: "p22",
    slug: "calca-jeans-reta-nova",
    name: "Calça Jeans Reta Nova",
    category: "calcas",
    subcategory: "jeans",
    brand: "km-essentials",
    price: 329.9,
    rating: 4.5,
    reviewsCount: 155,
    colors: [{ name: "Azul Escuro", hex: "#2C3546" }],
    sizes: ["36", "38", "40", "42", "44"],
    stock: "disponivel",
    description: "Denim rígido de lavagem escura, cintura alta e modelagem reta.",
    details: ["Cintura alta", "Lavagem escura"],
    composition: "100% Algodão",
    care,
    art: "pants",
    tone: 3,
    sold: 720,
    createdAt: "2026-04-22",
  },
  {
    id: "p23",
    slug: "bolsa-clutch-cetim-gala",
    name: "Clutch Cetim Gala",
    category: "acessorios",
    subcategory: "bolsas",
    brand: "km-noir",
    price: 399.9,
    oldPrice: 459.9,
    rating: 4.8,
    reviewsCount: 33,
    colors: [
      { name: "Champagne", hex: "#D8C3A5" },
      { name: "Preto", hex: "#0D0D0D" },
    ],
    sizes: ["Único"],
    stock: "disponivel",
    description: "Cetim drapeado com fecho joia e corrente dourada removível.",
    details: ["Fecho joia", "Corrente removível"],
    composition: "Cetim de seda",
    care: ["Guardar no dust bag"],
    art: "bag",
    tone: 1,
    sold: 180,
    createdAt: "2026-07-07",
  },
  {
    id: "p24",
    slug: "sandalia-tiras-douradas-sole",
    name: "Sandália Tiras Douradas Sole",
    category: "acessorios",
    subcategory: "calcados",
    brand: "maison-dore",
    price: 459.9,
    rating: 4.6,
    reviewsCount: 48,
    colors: [
      { name: "Dourado", hex: "#C6A15B" },
      { name: "Preto", hex: "#0D0D0D" },
    ],
    sizes: ["34", "35", "36", "37", "38", "39"],
    stock: "disponivel",
    isNew: true,
    description: "Tiras finas metalizadas, salto bloco 7cm e fivela ajustável.",
    details: ["Salto bloco 7cm", "Fivela ajustável"],
    composition: "Couro metalizado",
    care: ["Limpar com flanela"],
    art: "heels",
    tone: 0,
    sold: 230,
    createdAt: "2026-09-27",
  },
];

export const reviews: Review[] = [
  {
    id: "r1",
    productId: "p1",
    author: "Juliana M.",
    rating: 5,
    title: "Caimento perfeito",
    body: "O cetim é lindíssimo e o corte enviesado valoriza muito. Usei em um casamento e recebi elogios a noite toda.",
    date: "2026-09-12",
    size: "P",
    fit: "perfeito",
    verified: true,
    helpful: 24,
  },
  {
    id: "r2",
    productId: "p1",
    author: "Beatriz A.",
    rating: 5,
    title: "Acabamento impecável",
    body: "Chegou em uma embalagem linda, com cheirinho. O tecido é encorpado e não amassa fácil.",
    date: "2026-08-30",
    size: "M",
    fit: "perfeito",
    verified: true,
    helpful: 12,
  },
  {
    id: "r3",
    productId: "p1",
    author: "Camila R.",
    rating: 4,
    title: "Lindo, mas veste um pouco grande",
    body: "Amei a cor champagne. Recomendo pegar um número abaixo se estiver entre dois tamanhos.",
    date: "2026-08-14",
    size: "M",
    fit: "grande",
    verified: true,
    helpful: 9,
  },
  {
    id: "r4",
    productId: "p3",
    author: "Fernanda L.",
    rating: 5,
    title: "Minha calça favorita",
    body: "Já tenho em duas cores. Alonga muito e é confortável para o dia inteiro no escritório.",
    date: "2026-09-02",
    size: "38",
    fit: "perfeito",
    verified: true,
    helpful: 31,
  },
  {
    id: "r5",
    productId: "p4",
    author: "Patrícia S.",
    rating: 5,
    title: "Vale cada centavo",
    body: "Estrutura de blazer importado. Os botões dourados dão um toque muito chique.",
    date: "2026-07-21",
    size: "M",
    fit: "perfeito",
    verified: true,
    helpful: 17,
  },
];

export const questions: Question[] = [
  {
    id: "q1",
    productId: "p1",
    author: "Larissa",
    question: "O tecido é transparente na cor nude?",
    answer:
      "Olá, Larissa! O vestido possui forro interno em todas as cores, então não há transparência. Beijos, equipe Karen Michelly.",
    date: "2026-09-10",
  },
  {
    id: "q2",
    productId: "p1",
    author: "Renata",
    question: "Qual o comprimento do tamanho M?",
    answer: "Oi, Renata! No tamanho M o comprimento é de 118cm do ombro à barra.",
    date: "2026-08-22",
  },
  {
    id: "q3",
    productId: "p1",
    author: "Paula",
    question: "Tem previsão de chegar na cor verde?",
    date: "2026-10-01",
  },
];

export const coupons: Coupon[] = [
  {
    code: "BEMVINDA10",
    title: "10% na primeira compra",
    description: "Válido para novas clientes em todo o site.",
    type: "percent",
    value: 10,
    minValue: 0,
    expiresAt: "2026-12-31",
    status: "ativo",
  },
  {
    code: "KMFRETE",
    title: "Frete grátis",
    description: "Frete grátis para compras acima de R$ 399.",
    type: "shipping",
    value: 0,
    minValue: 399,
    expiresAt: "2026-11-30",
    status: "ativo",
  },
  {
    code: "GOLD150",
    title: "R$ 150 OFF",
    description: "Desconto fixo em compras acima de R$ 1.200.",
    type: "fixed",
    value: 150,
    minValue: 1200,
    expiresAt: "2026-10-31",
    status: "ativo",
  },
  {
    code: "DESCULPA15",
    title: "15% de compensação",
    description: "Um pedido de desculpas pelo atraso na sua entrega.",
    type: "percent",
    value: 15,
    minValue: 0,
    expiresAt: "2026-12-31",
    status: "ativo",
  },
  {
    code: "VERAO20",
    title: "20% em Moda Praia",
    description: "Campanha de verão encerrada.",
    type: "percent",
    value: 20,
    minValue: 0,
    expiresAt: "2026-03-01",
    status: "expirado",
  },
  {
    code: "ANIVER15",
    title: "15% de aniversário",
    description: "Presente de aniversário já utilizado.",
    type: "percent",
    value: 15,
    minValue: 0,
    expiresAt: "2026-09-30",
    status: "usado",
  },
];

export const addresses: Address[] = [
  {
    id: "a1",
    label: "Casa",
    recipient: "Karen Michelly",
    zip: "01310-100",
    street: "Avenida Paulista",
    number: "1578",
    complement: "Apto 142",
    district: "Bela Vista",
    city: "São Paulo",
    state: "SP",
    phone: "(11) 98765-4321",
    isDefault: true,
  },
  {
    id: "a2",
    label: "Trabalho",
    recipient: "Karen Michelly",
    zip: "04538-133",
    street: "Avenida Brigadeiro Faria Lima",
    number: "3477",
    complement: "14º andar",
    district: "Itaim Bibi",
    city: "São Paulo",
    state: "SP",
    phone: "(11) 3456-7890",
  },
];

export const orders: Order[] = [
  {
    id: "KM-240918",
    date: "2026-10-01",
    status: "transporte",
    items: [
      { productId: "p1", size: "P", color: "Champagne", qty: 1, price: 689.9 },
      { productId: "p11", size: "Único", color: "Dourado", qty: 1, price: 289.9 },
    ],
    shipping: 0,
    discount: 68.99,
    payment: "cartao",
    addressId: "a1",
    carrier: "Transportadora Expressa",
    tracking: "BR938475612KM",
    estimated: "2026-10-07",
  },
  {
    id: "KM-240877",
    date: "2026-09-22",
    status: "entregue",
    items: [{ productId: "p3", size: "38", color: "Preto", qty: 1, price: 429.9 }],
    shipping: 24.9,
    discount: 0,
    payment: "pix",
    addressId: "a1",
    carrier: "Correios SEDEX",
    tracking: "QB123456789BR",
    estimated: "2026-09-27",
  },
  {
    id: "KM-240850",
    date: "2026-09-29",
    status: "preparacao",
    items: [{ productId: "p4", size: "M", color: "Preto", qty: 1, price: 899.9 }],
    shipping: 0,
    discount: 0,
    payment: "pix",
    addressId: "a2",
    carrier: "Transportadora Expressa",
    tracking: "",
    estimated: "2026-10-09",
  },
  {
    id: "KM-240712",
    date: "2026-09-05",
    status: "atrasado",
    items: [{ productId: "p6", size: "Único", color: "Preto", qty: 1, price: 1290 }],
    shipping: 0,
    discount: 150,
    payment: "cartao",
    addressId: "a1",
    carrier: "Correios PAC",
    tracking: "QB998877665BR",
    estimated: "2026-09-20",
  },
  {
    id: "KM-240650",
    date: "2026-08-18",
    status: "cancelado",
    items: [{ productId: "p13", size: "M", color: "Nude", qty: 2, price: 239.9 }],
    shipping: 19.9,
    discount: 0,
    payment: "boleto",
    addressId: "a1",
    carrier: "Correios PAC",
    tracking: "",
    estimated: "2026-08-28",
  },
];

export const shippingOptions: ShippingOption[] = [
  { id: "economico", name: "Econômico", carrier: "Correios PAC", days: "6 a 9 dias úteis", price: 19.9 },
  { id: "expresso", name: "Expresso", carrier: "Correios SEDEX", days: "2 a 4 dias úteis", price: 34.9 },
  { id: "premium", name: "Entrega Premium", carrier: "Motoboy KM", days: "Em até 24h (capitais)", price: 49.9 },
  { id: "retirada", name: "Retirar no Atelier", carrier: "Loja Jardins, SP", days: "Pronto em 2h", price: 0 },
];

export const blogAuthors: BlogAuthor[] = [
  {
    slug: "karen-michelly",
    name: "Karen Michelly",
    role: "Fundadora & Diretora Criativa",
    bio: "Estilista com 15 anos de experiência em moda feminina, apaixonada por alfaiataria e por vestir mulheres reais com elegância.",
  },
  {
    slug: "marina-lopes",
    name: "Marina Lopes",
    role: "Editora de Moda",
    bio: "Jornalista de moda, escreve sobre tendências, consumo consciente e styling para o dia a dia.",
  },
];

export const blogCategories = [
  { slug: "tendencias", name: "Tendências" },
  { slug: "styling", name: "Styling" },
  { slug: "bastidores", name: "Bastidores" },
  { slug: "cuidados", name: "Cuidados com a peça" },
];

const sampleBody: BlogPost["body"] = [
  {
    type: "p",
    text: "A elegância não está no excesso, mas na intenção. Cada peça que escolhemos conta uma história sobre quem somos e sobre como queremos ocupar os espaços.",
  },
  { type: "h2", text: "Comece pelo essencial" },
  {
    type: "p",
    text: "Uma boa calça de alfaiataria, uma camisa de seda e um blazer bem cortado formam a base de um guarda-roupa que funciona em qualquer estação.",
  },
  {
    type: "list",
    text: [
      "Invista em tecidos naturais e de toque agradável",
      "Prefira cores neutras que conversam entre si",
      "Use o dourado como ponto de luz, nunca como protagonista",
    ],
  },
  {
    type: "quote",
    text: "Vestir-se bem é uma forma silenciosa de cuidado consigo mesma.",
  },
  { type: "h2", text: "Os detalhes que assinam o look" },
  {
    type: "p",
    text: "Um colar fino, um brinco de pérola, um scarpin de bico fino. São os detalhes que transformam um visual simples em uma composição memorável.",
  },
];

export const blogPosts: BlogPost[] = [
  {
    slug: "guarda-roupa-capsula-elegante",
    title: "Guarda-roupa cápsula: 10 peças para uma elegância sem esforço",
    excerpt: "Como montar uma base versátil que combina entre si e resolve todas as ocasiões.",
    category: "styling",
    author: "karen-michelly",
    date: "2026-09-28",
    readTime: 6,
    art: "blazer",
    tone: 0,
    body: sampleBody,
  },
  {
    slug: "tendencias-primavera-verao-2027",
    title: "Primavera Verão 2027: o que vem por aí",
    excerpt: "Linho, tons de areia e o retorno da cintura marcada. As apostas da estação.",
    category: "tendencias",
    author: "marina-lopes",
    date: "2026-09-20",
    readTime: 5,
    art: "dress",
    tone: 1,
    body: sampleBody,
  },
  {
    slug: "como-cuidar-da-seda",
    title: "Como cuidar das suas peças de seda",
    excerpt: "Lavagem, secagem e armazenamento para que a sua seda dure por anos.",
    category: "cuidados",
    author: "marina-lopes",
    date: "2026-09-08",
    readTime: 4,
    art: "blouse",
    tone: 2,
    body: sampleBody,
  },
  {
    slug: "bastidores-colecao-aurora",
    title: "Bastidores da coleção Aurora",
    excerpt: "Do primeiro croqui à última prova: uma visita ao nosso ateliê.",
    category: "bastidores",
    author: "karen-michelly",
    date: "2026-08-30",
    readTime: 7,
    art: "jumpsuit",
    tone: 3,
    body: sampleBody,
  },
  {
    slug: "looks-de-festa-noite",
    title: "Cinco looks de festa para noites inesquecíveis",
    excerpt: "Do casamento ao jantar de gala, produções para brilhar com sofisticação.",
    category: "styling",
    author: "karen-michelly",
    date: "2026-08-15",
    readTime: 5,
    art: "heels",
    tone: 1,
    body: sampleBody,
  },
  {
    slug: "acessorios-dourados-como-usar",
    title: "Dourado na medida certa: como usar acessórios",
    excerpt: "O ponto de luz que eleva o look sem pesar a produção.",
    category: "tendencias",
    author: "marina-lopes",
    date: "2026-08-02",
    readTime: 3,
    art: "necklace",
    tone: 0,
    body: sampleBody,
  },
];

export const faqs = [
  {
    group: "Pedidos",
    items: [
      {
        q: "Como acompanho o meu pedido?",
        a: "Acesse Minha Conta > Meus Pedidos e clique em Rastrear. Você também recebe atualizações por e-mail e WhatsApp.",
      },
      {
        q: "Posso alterar o endereço após a compra?",
        a: "Sim, enquanto o pedido estiver em preparação. Fale com o nosso atendimento pelo WhatsApp.",
      },
    ],
  },
  {
    group: "Pagamentos",
    items: [
      {
        q: "Quais formas de pagamento são aceitas?",
        a: "Cartões de crédito em até 6x sem juros, PIX com 5% de desconto e boleto bancário.",
      },
      {
        q: "O pagamento via PIX é seguro?",
        a: "Sim. O QR Code é gerado pelo nosso parceiro de pagamentos e a confirmação é instantânea.",
      },
    ],
  },
  {
    group: "Trocas e devoluções",
    items: [
      {
        q: "Qual o prazo para troca?",
        a: "Você tem até 30 dias após o recebimento para solicitar a troca, e a primeira troca é gratuita.",
      },
      {
        q: "Como funciona o reembolso?",
        a: "Após recebermos e analisarmos a peça, o reembolso é feito na mesma forma de pagamento em até 10 dias úteis.",
      },
    ],
  },
  {
    group: "Produtos",
    items: [
      {
        q: "Como escolher o tamanho ideal?",
        a: "Cada produto possui uma tabela de medidas. Em caso de dúvida, nossa consultora de estilo ajuda pelo WhatsApp.",
      },
    ],
  },
];

export const stores = [
  { city: "São Paulo", name: "Atelier Jardins", address: "Rua Oscar Freire, 1020", hours: "Seg a Sáb, 10h às 20h" },
  { city: "Rio de Janeiro", name: "Leblon", address: "Rua Dias Ferreira, 300", hours: "Seg a Sáb, 10h às 20h" },
];

/* Helpers ---------------------------------------------------------- */
export const getProduct = (idOrSlug: string) =>
  products.find((p) => p.id === idOrSlug || p.slug === idOrSlug);
export const getCategory = (slug: string) => categories.find((c) => c.slug === slug);
export const getBrand = (slug: string) => brands.find((b) => b.slug === slug);
export const getOrder = (id: string) => orders.find((o) => o.id === id);
export const getAddress = (id: string) => addresses.find((a) => a.id === id);
export const getPost = (slug: string) => blogPosts.find((p) => p.slug === slug);
export const getAuthor = (slug: string) => blogAuthors.find((a) => a.slug === slug);
export const discountPercent = (p: Product) =>
  p.oldPrice ? Math.round((1 - p.price / p.oldPrice) * 100) : 0;
export const relatedProducts = (p: Product, n = 4) =>
  products.filter((x) => x.id !== p.id && x.category === p.category).slice(0, n);
export const similarProducts = (p: Product, n = 4) =>
  products
    .filter((x) => x.id !== p.id && (x.art === p.art || x.brand === p.brand))
    .slice(0, n);
export const onSale = () => products.filter((p) => p.oldPrice);
export const newArrivals = () =>
  [...products].sort((a, b) => b.createdAt.localeCompare(a.createdAt)).slice(0, 12);
export const bestsellers = () => [...products].sort((a, b) => b.sold - a.sold).slice(0, 12);
export const searchProducts = (q: string) => {
  const t = q
    .toLowerCase()
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .trim();
  if (!t) return [];
  return products.filter((p) =>
    `${p.name} ${p.category} ${p.subcategory} ${p.brand} ${p.colors.map((c) => c.name).join(" ")}`
      .toLowerCase()
      .normalize("NFD")
      .replace(/[̀-ͯ]/g, "")
      .includes(t)
  );
};
export const popularSearches = ["vestido midi", "alfaiataria", "seda", "blazer", "dourado", "linho"];
